### ISSUE TITLE
#4 - Introduce proper naming on passed name parameters

### ISSUE THREAD

**Issue by deeleman** [deeleman/angular-schematics-talk#4]
Update current implementation to ensure that project names passed as Pascal-cased names become kebab-cased when generating paths and folders.

This will allow to introduce Schematic helpers such as `classify` or `dasherize`.

The idea is that runnign this:

```
$ schematics .:aliased-app --name=myNamedProject
```

Would lead to paths such as 

```
import * from '@my-named-project/etc'
```

Or SASS imports such as:

`@import "@my-named-project/core"`

**Comment by anfibiacreativa** [comment]
Actually this is done, although there is another issue with path resolution, that in my case may be a VScode/tslint config combo bug
